import Link from 'next/link';
import { Button, Paper, HandwrittenNote, SketchArrow } from 'sketchpad-ui';
import { BrandLogo } from '../../components/BrandLogo';
import { CodeBlock } from '../../components/DocPage';
import { components, shippedCount } from '../../lib/docs-config';

export const metadata = { title: 'Introduction' };

export default function IntroductionPage() {
  return (
    <article className="docArticle">
      <Paper seed="hero" tapePinned foldedCorner className="introHero">
        <div className="heroHeader">
          <BrandLogo size={72} showWordmark={false} asLink={false} className="heroLogo" />
          <div>
            <h1 className="docTitle">Sketchpad UI</h1>
            <p className="docDescription">
              Production-quality React components with a pen-on-paper wireframe aesthetic. Copy-friendly,
              accessible, and fully documented.
            </p>
          </div>
        </div>
        <div className="introActions">
          <Link href="/docs/installation">
            <Button variant="primary" seed="hero-cta">
              Get started
            </Button>
          </Link>
          <Link href="/docs/components">
            <Button variant="ghost" seed="hero-docs">
              Browse {components.length} components
            </Button>
          </Link>
        </div>
        <div className="introNote">
          <SketchArrow width={28} height={28} seed="hero-arrow" />
          <HandwrittenNote>{shippedCount} shipped today · deterministic SVG paths · zero runtime deps</HandwrittenNote>
        </div>
      </Paper>

      <section className="docSection">
        <HandwrittenNote className="docSectionTitle">Why Sketchpad UI?</HandwrittenNote>
        <div className="featureGrid">
          <Paper seed="feat-sketch" className="featureCard">
            <h3>Sketch-native</h3>
            <p>Every border is generated by our path engine: seeded, cacheable, and consistent across SSR and CSR.</p>
          </Paper>
          <Paper seed="feat-parity" className="featureCard">
            <h3>Complete catalog</h3>
            <p>Forms, navigation, overlays, data display, and chat primitives on the roadmap.</p>
          </Paper>
          <Paper seed="feat-a11y" className="featureCard">
            <h3>Accessible first</h3>
            <p>Real semantic controls under decorative SVG. Keyboard, ARIA, and WCAG contrast baked in.</p>
          </Paper>
        </div>
      </section>

      <section className="docSection">
        <HandwrittenNote className="docSectionTitle">Quick install</HandwrittenNote>
        <CodeBlock code="npm install sketchpad-ui @sketchpad/tokens" />
      </section>
    </article>
  );
}
